baseURL: "https://lbroomfield.netlify.app/"
languageCode: "en-us"
title: "lbroomfield"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Latoya Broomfield Profile"
  description: My personal site.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Latoya Broomfield" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Latoya."
    subtitle: "Bridging Healthcare Insights with Data Science"
    content: "With a solid foundation in healthcare informatics and revenue cycle, I am venturing into the realm of Data Analytics and Data Science to leverage my analytical skills and contribute to data-driven decision making in healthcare."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/lbroomfield
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/latoya-broomfield-rhia-ccs-45739b171/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      With an extensive background in medical coding and healthcare informatics, I've dedicated my career to ensuring accuracy and compliance in medical record documentation. 
      
      My experience spans across various healthcare settings including inpatient, outpatient, and rehabilitation facilities. I'm proficient in ICD-10 CM, CPT, DRG, and modifier assignment, and have played a pivotal role in training and mentoring new coders. 
      
      I am keen on transitioning to a role in Data Analytics and Data Science. My foundation in healthcare data, SQL, Python, and statistical analysis, coupled with a relentless curiosity, equip me to drive insights that foster data-driven decision making in healthcare.


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: Outpatient Medical Coding Specialist
        company: Gebbs Healthcare Solutions
        date: 2022 - Present
        content: |-
          At Gebbs, I conduct meticulous medical records analysis for outpatient healthcare records, ensuring accurate coding and data abstraction in accordance with official coding guidelines. My responsibilities also include ensuring proper ICD-10 CM, CPT, I&I, E/M and modifier assignment.
  
      - job: Medical Coding Specialist
        company: Aquity Solutions (formerly MModal)
        date: 2016 - 2022
        content: |-
          Worked on comprehensive medical record analysis for both inpatient and outpatient healthcare records, ensuring accurate coding and compliance with official coding guidelines. Provided training for new coders and assisted in transitioning between work queues/chart types, contributing to efficient charge capture practices.
  
      - job: Medical Coding Specialist
        company: iMedX
        date: 2017 - 2020
        content: |-
          Specialized in abstracting and analyzing data from inpatient rehab and outpatient healthcare records. Key contributor to HEDIS quality measures abstraction, aligning with health insurance providers' criteria.
    
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: Master of Science in Health Informatics
        school:
          name: University of Maryland, Global Campus
      - title: Bachelor of Science in Healthcare Management
        school:
          name: Clayton State University
      - title: Associate of Science in Health Information Technology
        school:
          name: Atlanta Technical College


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: COVID-19 Analysis
        content: A comprehensive analysis of COVID-19 data focusing on various aspects like the total cases, deaths, and vaccination rates across different locations and continents. 
        image: /images/projects/covid19analysis.png
        badges:
          - "SQL"
          - "Data Analysis"
        links:
          - icon: fab fa-github
            url: https://github.com/lbroomfield/PortfolioProjects/blob/main/Covidproject.sql  
            
      - title: Movie Features Correlation Analysis
        content: An analysis project exploring the correlations between different numerical features of movies.
        image: /images/projects/moviecurr.png
        badges:
          - "Python"
          - "Pandas"
          - "NumPy"
          - "Seaborn"
          - "Matplotlib"
          - "Data Analysis"
          - "Data Visualization"
        links:
          - icon: fab fa-github
            url: https://github.com/lbroomfield/PortfolioProjects/blob/main/Movie%20Correlation%20Project.ipynb
          
      - title: Medical Data Analysis (DRG Project)
        content: A statistical analysis and data visualization project conducted using R, focusing on medical data related to Diagnostic Related Groups (DRGs), Charge Capture Ratio (CCR), and Average Covered Charges.
        image: /images/projects/drg.png
        badges:
          - "R"
          - "Statistical Analysis"
          - "Data Visualization"
          - "Medical Data Analysis"
        links:
          - icon: fab fa-github
            url: https://github.com/lbroomfield/PortfolioProjects/blob/main/drgproject.Rmd

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: latoyabroomfield@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/lbroomfield
      linkedin: https://www.linkedin.com/in/latoya-broomfield-rhia-ccs-45739b171/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
